name: hello-world

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      platform:
        description: 'Platform to run appium tests on'
        required: true
        default: 'android'
        choices: ['android', 'ios']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hello World
        run: |
          echo "Hello, World!"
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "Platform: ${{ github.event.inputs.platform }}"
